org: mariliaglorenzato
app: aws-node
service: ms-users
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30

custom:
  # webpackIncludeModules: true
  esbuild:
    bundle: true
    minify: false
  serviceName: users
  baseApi: ${self:custom.serviceName}
  handlers: src/frameworks/handlers

functions:
  getUser:
    handler: ${self:custom.handlers}/getUser.getUser
    events:
      - http:
          path: ${self:custom.baseApi}/{userId}
          method: get
          cors:
            origin: '*'
            headers: '*'
plugins:
  - serverless-esbuild
  - serverless-offline
