app: ms-users
service: ms-users
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_URI: ${env:MONGO_URI}
    MS_AUTH_URL: ${env:MS_AUTH_URL}
  timeout: 30
custom:
  esbuild:
    bundle: true
    minify: false
  serviceName: ms-users
  baseApi: ${self:custom.serviceName}
  handlers: src/frameworks/handlers

functions:
  getUser:
    handler: ${self:custom.handlers}/getUser.getUser
    tracing: true
    url:
      authorizer: aws_iam
    events:
      - http:
          path: ${self:custom.baseApi}/{_id}
          method: get
          cors:
            origin: "*", 
            headers: 
              - "*"
  createUser:
    handler: ${self:custom.handlers}/createUser.createUser
    tracing: true
    events:
      - http:
          path: ${self:custom.baseApi}
          method: post
          cors:
            origin: "*"
            headers:
              - "*"
  updateUser:
    handler: ${self:custom.handlers}/updateUser.updateUser
    tracing: true
    url:
      authorizer: aws_iam
    events:
      - http:
          path: ${self:custom.baseApi}/{_id}
          method: put
          cors:
            origin: "*"
            headers: 
              - "*"

plugins:
  - serverless-esbuild
  - serverless-offline
